doctrine:
    dbal:
        url: '%env(string:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: 'doctrine.orm.naming_strategy.underscore_number_aware'
        auto_mapping: true
        mappings:
            App:
                dir: '%kernel.project_dir%/src/Doctrine/Entity'
                prefix: 'App\Doctrine\Entity'
                alias: 'App'
                is_bundle: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: 'pool'
                pool: 'doctrine.system_cache_pool'
            result_cache_driver:
                type: 'pool'
                pool: 'doctrine.result_cache_pool'

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: 'cache.app'
                doctrine.system_cache_pool:
                    adapter: 'cache.system'
