framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false

    session:
        storage_factory_id: 'session.storage.factory.native'
        handler_id: null
        cookie_secure: 'auto'
        cookie_samesite: 'lax'

    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: 'session.storage.factory.mock_file'
