controllers:
    resource: ../src/Controller/
    type: annotation

easy_admin_controllers:
    resource: ../src/EasyAdmin/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_logout:
    path: '/logout'
    methods:
        - 'GET'
        - 'POST'
